name: WeChat MiniProgram Demo CI/CD

on:
  push:
    branches:
      - feat-ce
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone submodule
        run: git submodule status

      - name: Install dependencies
        run: npm install

      - name: Run package script
        run: npm run init

      - name: Upload MiniProgram
        env:
          WX_PRIVATE_KEY: ${{ secrets.WX_PRIVATE_KEY }}
        run: |
          mkdir -p ./build
          echo "$WX_PRIVATE_KEY" > ./build/key
          cat ./build/key
